# Automatic Differentiation

### A Simple Example

In [1]:
import torch

In [2]:
x = torch.arange(4.0, requires_grad=True)
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [3]:
x.grad

In [4]:
y = 2 * torch.dot(x, x)
y

tensor(0., grad_fn=<MulBackward0>)

In [5]:
y.backward()

In [6]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [7]:
x.grad == 4 * x

tensor([True, True, True, True])

In [8]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

### Detaching Computation

In [9]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

In [10]:
z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [11]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

### Computing the Gradient of Python Control Flow

In [12]:
def f(a):
    b = a * 2
    while b.norm().item() < 1000:
        b = b * 2
    if b.sum().item() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [13]:
a = torch.randn(size=(1,), requires_grad=True)
d = f(a)
d.backward()

In [14]:
a.grad == (d / a)

tensor([True])